### ISSUE TITLE
Currency DB fix

### ISSUE THREAD

**Issue by martinnenseth** [Cmoen11/BuffBot#14]
Long story short 
... 
Expected behaviour 
... 
Actual Behaviour 
... 
Steps to reproduce 
... 
Your enviroment 
OS, ptyhon version and more if neccesarily

**Comment by mvenaas** [comment]
@martinnenseth The problem, I think,  lies in the database calls done in from [line 31 in database.py](https://github.com/Cmoen11/BuffBot/blob/master/BuffBot/database.py#L31) and onwards. 

I haven't looked closely at this issue, yet. 

There are currently 3 method calls currently commented out [here](https://github.com/Cmoen11/BuffBot/blob/master/BuffBot/currency.py#L15). Commented out to make the code run. Uncomment these and you will get the error we're talking about
