### ISSUE TITLE
Queue fix 

### ISSUE THREAD

**Issue by martinnenseth** [Cmoen11/BuffBot#34]
**Long story short** 
When a song in the queue is done (finished playing), the next one does not start automatically
**Expected behaviour** 
Start next song in queue.
**Actual Behaviour** 
Song nr.1 in the queue plays, finishes, and song nr. 2 does not automatically start.
**Steps to reproduce** 
1. !play "youtube-url"
2. !queue "youtube-url"
**Your enviroment** 
W10, Python 3.6

**Comment by Cmoen11** [comment]
This one is fixed.. aproved when pullrequest is made
