### ISSUE TITLE
Queuing songs

### ISSUE THREAD

**Issue by martinnenseth** [Cmoen11/BuffBot#4]
Instead of overriding the song being currently played, it would be nice if the bot queuing it instead, so that the current song would not get interuppted.

**Comment by martinnenseth** [comment]
Status? @Zhiftie

**Comment by Cmoen11** [comment]
There's an issue when the song in queue ends. Next in list do not start before !next is called.. is it possible to make it play the next song in the list automatically?

**Comment by Zhiftie** [comment]
Should be possible, not quite sure how yet.
